### ISSUE TITLE
Incompatible with jupyterlab 0.32.0?

### ISSUE THREAD

**Issue by liffiton** [quiltdata/jupyterlab#2]
I had this extension working with my jupyterlab install, but since upgrading jupyterlab to 0.32.0, the extension no longer works (the tab doesn't show up in the Jupyterlab interface).  I'm not certain the issue was caused by the upgrade to 0.32.0, but that's the only thing I recall changing.

I thought the extension might need to be reinstalled, so I re-ran ``jupyter labextension install jupyterlab-quilt``.  It fails with an error in semver:

```
$ jupyter labextension install jupyterlab-quilt --debug
Searching ['/share/apps/share/jupyter_env', '/root/.jupyter', '/share/apps/share/jupyter_env/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Looking for jupyter_config in /etc/jupyter
Looking for jupyter_config in /usr/local/etc/jupyter
Looking for jupyter_config in /share/apps/share/jupyter_env/etc/jupyter
Looking for jupyter_config in /root/.jupyter
Looking for jupyter_config in /share/apps/share/jupyter_env
> /share/apps/share/jupyter_env/bin/npm pack jupyterlab-quilt
jupyterlab-quilt-0.2.3.tgz
Traceback (most recent call last):

  File "/share/apps/share/jupyter_env/lib64/python3.6/site-packages/jupyterlab/labextensions.py", line 71, in start
    ans = self.run_task()

  File "/share/apps/share/jupyter_env/lib64/python3.6/site-packages/jupyterlab/labextensions.py", line 100, in run_task
    for arg in self.extra_args

  File "/share/apps/share/jupyter_env/lib64/python3.6/site-packages/jupyterlab/labextensions.py", line 100, in <listcomp>
    for arg in self.extra_args

  File "/share/apps/share/jupyter_env/lib64/python3.6/site-packages/jupyterlab/commands.py", line 227, in install_extension
    return handler.install_extension(extension)

  File "/share/apps/share/jupyter_env/lib64/python3.6/site-packages/jupyterlab/commands.py", line 366, in install_extension
    info = self._install_extension(extension, tempdir)

  File "/share/apps/share/jupyter_env/lib64/python3.6/site-packages/jupyterlab/commands.py", line 1126, in _install_extension
    errors = _validate_compatibility(extension, deps, core_data)

  File "/share/apps/share/jupyter_env/lib64/python3.6/site-packages/jupyterlab/commands.py", line 1414, in _validate_compatibility
    overlap = _test_overlap(core_deps[key], value)

  File "/share/apps/share/jupyter_env/lib64/python3.6/site-packages/jupyterlab/commands.py", line 1427, in _test_overlap
    cmp = _compare_ranges(spec1, spec2)

  File "/share/apps/share/jupyter_env/lib64/python3.6/site-packages/jupyterlab/commands.py", line 1443, in _compare_ranges
    r2 = Range(spec2, True)

  File "/share/apps/share/jupyter_env/lib64/python3.6/site-packages/jupyterlab/semver.py", line 715, in __init__
    raise ValueError("Invalid SemVer Range: {}".format(range_))

ValueError: Invalid SemVer Range: latest


Errored, use --debug for full output:
ValueError: Invalid SemVer Range: latest
```

**Comment by akarve** [comment]
Thanks for the bug report. @meffij to investigate.

**Comment by meffij** [comment]
@liffiton Can you see if a fresh install from `master` fixes your issue? Please also update `quilt` with this command -- `pip install git+https://github.com/quiltdata/quilt.git#subdirectory=compiler`. [This commit](https://github.com/quiltdata/jupyterlab/commit/978df548fc60a34b23ba5a2614b6f8711593d183) should do the trick. Thanks for the report!

**Comment by liffiton** [comment]
I updated `quilt` as directed and cloned this repository.  The install (or at least, using the `jupyter labextension link .` command in the repository directory) now works.

But now the Quilt side-tab doesn't show up, and the jupyterhub process reports errors trying to build the extension, as far as I can tell.  

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jupyterlab-quilt@0.2.3 build: `tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jupyterlab-quilt@0.2.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     [path to debug log file]
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jupyterlab-quilt@0.2.3 prepare: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jupyterlab-quilt@0.2.3 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     [path to debug log file]
```

I don't know nearly enough about node/npm to try to guess as to what is going on there.  I can open a separate issue for that if that would be better.

**Comment by meffij** [comment]
@liffiton I think I've identified the issue. Please `git pull` the extension, and run `npm install` before `jupyter labextension install`. Thanks for your help in making progress on this issue!

**Comment by liffiton** [comment]
I still get the same error.

And I'm sorry, I hadn't paid enough attention to errors in the `npm run watch` step of the install (I had assumed they were warnings).  It looks like `tsc` is failing with a bunch of errors like:

```
$ npm run watch

> jupyterlab-quilt@0.2.3 watch /share/apps/share/jupyter_env/src/quilt-jupyterlab
> tsc -w

node_modules/@jupyterlab/apputils/node_modules/@types/react/index.d.ts(3743,19): error TS2320: Interface 'Element' cannot simultaneously extend types 'ReactElement<any>' and 'ReactElement<any>'.
  Named property 'type' of types 'ReactElement<any>' and 'ReactElement<any>' are not identical.
node_modules/@jupyterlab/apputils/node_modules/@types/react/index.d.ts(3744,19): error TS2320: Interface 'ElementClass' cannot simultaneously extend types 'Component<any, {}>' and 'Component<any, {}, any>'.
  Named property 'componentDidUpdate' of types 'Component<any, {}>' and 'Component<any, {}, any>' are not identical.
node_modules/@jupyterlab/apputils/node_modules/@types/react/index.d.ts(3744,19): error TS2320: Interface 'ElementClass' cannot simultaneously extend types 'Component<any, {}>' and 'Component<any, {}, any>'.
  Named property 'refs' of types 'Component<any, {}>' and 'Component<any, {}, any>' are not identical.
node_modules/@jupyterlab/apputils/node_modules/@types/react/index.d.ts(3753,19): error TS2320: Interface 'IntrinsicClassAttributes<T>' cannot simultaneously extend types 'ClassAttributes<T>' and 'ClassAttributes<T>'.
  Named property 'ref' of types 'ClassAttributes<T>' and 'ClassAttributes<T>' are not identical.
node_modules/@types/react/index.d.ts(2250,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'a' must be of type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>', but here has type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.
node_modules/@types/react/index.d.ts(2251,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'abbr' must be of type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>', but here has type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'.
node_modules/@types/react/index.d.ts(2252,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'address' must be of type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>', but here has type 'DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>'.
node_modules/@types/react/index.d.ts(2253,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'area' must be of type 'DetailedHTMLProps<AreaHTMLAttributes<HTMLAreaElement>, HTMLAreaElement>', but here has type 'DetailedHTMLProps<AreaHTMLAttributes<HTMLAreaElement>, HTMLAreaElement>'.
[many more like those reported...]
```

And as far as I can tell, this is the same set of errors that trips it up when jupyterhub tries to build the extension after I've installed it.

[Tangential side note: could the `npm run watch` step in the README dev install instructions be `npm run build`?  The former never exits, while the latter seems to do the same thing but does exit and more clearly reports failure.]

**Comment by meffij** [comment]
@liffiton I have reproduced your issue. I am working on a fix now.

`npm run watch` lets you edit the extension and it live-reloads, for development purposes. For normal users of the extension, I agree that `npm run build` is sufficient. It actually runs during the `jupyter labextension install` step if I'm not mistaken.

Thanks for your fast responses!

**Comment by meffij** [comment]
@liffiton I think I've solved your issue. Please run `jupyter labextension uninstall jupyterlab-quilt`, then delete your `node_modules` folder, then pull the latest version of `jupyterlab-quilt`, then run `npm run build`, then `jupyter labextension install`. I believe the issue was with conflicting type declarations between jupyterlab and the extension.

**Comment by liffiton** [comment]
Yes, that fixed that problem.  The extension now builds and installs properly.

Now when I open jupyterlab via jupyterhub, I get an error when it tries to build the extension (again?):

```
[I 2018-04-27 16:36:43.359 SingleUserNotebookApp process:70] > [path to env]/bin/npm pack [path to env]/src/quilt-jupyterlab

> jupyterlab-quilt@0.2.3 prepare [path to env]/src/quilt-jupyterlab
> npm run build


> jupyterlab-quilt@0.2.3 build [path to env]/src/quilt-jupyterlab
> tsc

error TS5033: Could not write file '[path to env]/src/quilt-jupyterlab/lib/index.d.ts': EACCES: permission denied, open '[path to env]/src/quilt-jupyterlab/lib/index.d.ts'.
error TS5033: Could not write file '[path to env]/src/quilt-jupyterlab/lib/index.js': EACCES: permission denied, open '[path to env]/src/quilt-jupyterlab/lib/index.js'.
```

I _think_ it's trying to do `npm run build` as my user (the one I've logged into Jupyterhub as), which does not have write access to the extension's files, as they're owned by root.  The log file it creates for this error is in my user's `~/.npm/_logs/` folder, at least.

I'm guessing this is specific to running jupyterlab via jupyterhub, but I'm not sure why it wasn't a problem earlier -- again, the extension worked fine for me when running jupyterlab via jupyterhub before I updated jupyterlab.  Perhaps that was because I had installed the extension via the "official" channel vs building it and installing it from the repository as I'm doing now to test it?

**Comment by meffij** [comment]
That's interesting. I don't have any experience with jupyterhub personally. I will update the npm version of the extension so you can see if using npm resolves your issue.

**Comment by meffij** [comment]
0.2.4 is live on npm, give that a try.

**Comment by liffiton** [comment]
Installed with `jupyter labextension install jupyterlab-quilt`, and it works perfectly!  Thanks!
