### ISSUE TITLE
Installing labextension hangs on 'Resolving packages....'

### ISSUE THREAD

**Issue by robnewman** [quiltdata/jupyterlab#3]
I am trying to install the Jupyterlab extension for Quiltdata, but it appears to be failing:

Python version: 3.6.5
Pip version: 9.0.3

I have everything in a virtual environment (including Quilt and Jupyter):

$ pip freeze
appdirs==1.4.3
appnope==0.1.0
backcall==0.1.0
bleach==2.1.3
certifi==2018.4.16
chardet==3.0.4
decorator==4.3.0
entrypoints==0.2.3
future==0.16.0
html5lib==1.0.1
idna==2.7
ipykernel==4.8.2
ipython==6.4.0
ipython-genutils==0.2.0
ipywidgets==7.2.1
jedi==0.12.0
Jinja2==2.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyterlab==0.32.1
jupyterlab-launcher==0.10.5
MarkupSafe==1.0
mistune==0.8.3
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.5.0
numpy==1.14.5
packaging==17.1
pandas==0.23.1
pandocfilters==1.4.2
parso==0.2.1
pexpect==4.6.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
pyarrow==0.7.1
Pygments==2.2.0
pyparsing==2.2.0
python-dateutil==2.7.3
pytz==2018.4
PyYAML==3.12
pyzmq==17.0.0
qtconsole==4.3.1
quilt==2.9.6
requests==2.19.1
Send2Trash==1.5.0
simplegeneric==0.8.1
six==1.11.0
terminado==0.8.1
testpath==0.3.1
tornado==5.0.2
tqdm==4.23.4
traitlets==4.3.2
urllib3==1.23
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.2.1
xlrd==1.1.0

> pip install jupyterlab
Collecting jupyterlab
  Downloading https://files.pythonhosted.org/packages/49/fd/80c5243895ce01c48ccb65546c4aa9f2387633390b8baa0046d36998e17c/jupyterlab-0.32.1-py2.py3-none-any.whl (13.4MB)
    100% |████████████████████████████████| 13.4MB 92kB/s 

works fine, but then the following command hangs: 

$ jupyter labextension install jupyterlab-quilt
> /usr/local/bin/npm pack jupyterlab-quilt
npm notice 
npm notice 📦  jupyterlab-quilt@0.2.4
npm notice === Tarball Contents === 
npm notice 862B  package.json   
npm notice 1.0kB README.md      
npm notice 6.3kB lib/index.js   
npm notice 231B  lib/index.d.ts 
npm notice 0     style/index.css
npm notice === Tarball Details === 
npm notice name:          jupyterlab-quilt                        
npm notice version:       0.2.4                                   
npm notice filename:      jupyterlab-quilt-0.2.4.tgz              
npm notice package size:  3.0 kB                                  
npm notice unpacked size: 8.4 kB                                  
npm notice shasum:        c1fa5ec843df07f582a577304444d06226adb32a
npm notice integrity:     sha512-uV7bhjm3S2WNO[...]Ya+5ethrJH0ug==
npm notice total files:   5                                       
npm notice 
jupyterlab-quilt-0.2.4.tgz
> node /path/to/venv/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.5.1
(node:64192) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info No lockfile found.
[1/4] 🔍  Resolving packages...
⠄ jupyterlab-quilt@file:../extensions/jupyterlab-quilt-0.2.4.tgz

Thanks in advance!

**Comment by meffij** [comment]
Thanks for reporting this issue! What operating system are you running? It seems like the process hangs when trying to access the extension tarball on your local filesystem, which is interesting.

**Comment by robnewman** [comment]
Hi @meffij,

My operating system is macOS High Sierra (10.13.5).

My NPM was installed using Homebrew. Info:

    $ npm version
    { npm: '6.1.0',
      ares: '1.14.0',
      cldr: '33.0',
      http_parser: '2.8.0',
      icu: '61.1',
      modules: '64',
      napi: '3',
      nghttp2: '1.29.0',
      node: '10.3.0',
      openssl: '1.1.0h',
      tz: '2018c',
      unicode: '10.0',
      uv: '1.20.3',
      v8: '6.6.346.32-node.9',
      zlib: '1.2.11' }

Thanks,
Rob

**Comment by meffij** [comment]
We tried to reproduce the issue on a Mac and failed. I would recommend clearing everything out and trying again, just in case it was flakiness on any network resources. If that doesn't work, I found [this thread](https://github.com/jupyterhub/jupyterlab-hub/issues/58) which may be of help. Thanks for your help in diagnosing this issue, please let us know either way how it goes.

**Comment by robnewman** [comment]
Thanks for the help @meffij and I wanted to give you an update!

I tried to override the version of `yarn` installed as per your linked thread. However that didn't work -- same problem.

I am **99%** sure the problem is related to the fact that I am using a `virtualenv` for quilt (because I wanted to use the latest 3.6.5 Python and not 2.7 which is what my Anaconda install uses):

    (quilt-py3) $ which jupyter
    /path/to/venv/quilt-py3/bin/jupyter
    (quilt-py3) $ python -V
    Python 3.6.5

When I try to install the quilt extension to jupyterlab (with the `debug` flag added!):

    $ jupyter labextension install --debug jupyterlab-quilt
    Searching [u'/Users/rnewman/sandbox/quilt', '/Users/rnewman/.jupyter', '/anaconda2/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
    Looking for jupyter_config in /etc/jupyter
    Looking for jupyter_config in /usr/local/etc/jupyter
    Looking for jupyter_config in /anaconda2/etc/jupyter
    Looking for jupyter_config in /Users/rnewman/.jupyter
    Looking for jupyter_config in /Users/rnewman/sandbox/quilt
    > /usr/local/bin/npm pack jupyterlab-quilt
    npm notice 
    npm notice 📦  jupyterlab-quilt@0.2.4
    npm notice === Tarball Contents === 
    npm notice 862B  package.json   
    npm notice 1.0kB README.md      
    npm notice 6.3kB lib/index.js   
    npm notice 231B  lib/index.d.ts 
    npm notice 0     style/index.css
    npm notice === Tarball Details === 
    npm notice name:          jupyterlab-quilt                        
    npm notice version:       0.2.4                                   
    npm notice filename:      jupyterlab-quilt-0.2.4.tgz              
    npm notice package size:  3.0 kB                                  
    npm notice unpacked size: 8.4 kB                                  
    npm notice shasum:        c1fa5ec843df07f582a577304444d06226adb32a
    npm notice integrity:     sha512-uV7bhjm3S2WNO[...]Ya+5ethrJH0ug==
    npm notice total files:   5                                       
    npm notice 
    jupyterlab-quilt-0.2.4.tgz
    Traceback (most recent call last):
    
      File "/anaconda2/lib/python2.7/site-packages/jupyterlab/labextensions.py", line 71, in start
        ans = self.run_task()
    
      File "/anaconda2/lib/python2.7/site-packages/jupyterlab/labextensions.py", line 100, in run_task
        for arg in self.extra_args
    
      File "/anaconda2/lib/python2.7/site-packages/jupyterlab/commands.py", line 210, in install_extension
        return handler.install_extension(extension)
    
      File "/anaconda2/lib/python2.7/site-packages/jupyterlab/commands.py", line 347, in install_extension
        info = self._install_extension(extension, tempdir)
    
      File "/anaconda2/lib/python2.7/site-packages/jupyterlab/commands.py", line 1112, in _install_extension
        raise ValueError(msg)
    
    ValueError: 
    "jupyterlab-quilt@0.2.4" is not compatible with the current JupyterLab
    Conflicting Dependencies:
    JupyterLab              Extension            Package
    >=0.15.4-0 <0.16.0-0    >=0.16.0-0 <0.17.0-0 @jupyterlab/application
    >=0.15.4-0 <0.16.0-0    >=0.16.0-0 <0.17.0-0 @jupyterlab/notebook
    
    
    
    Errored, use --debug for full output:
    ValueError: 
    "jupyterlab-quilt@0.2.4" is not compatible with the current JupyterLab
    Conflicting Dependencies:
    JupyterLab              Extension            Package
    >=0.15.4-0 <0.16.0-0    >=0.16.0-0 <0.17.0-0 @jupyterlab/application
    >=0.15.4-0 <0.16.0-0    >=0.16.0-0 <0.17.0-0 @jupyterlab/notebook

So it appears that the node package manager is looking at an old version of `jupyterlab` that I have as part of my original (and old) Anaconda install and ignoring my shiny new `jupyterlab` that I have in my virtual environment. Unless you have encountered this before, I am going to go down the `jupyter config file` and `jupyterlab config file` rabbit hole! :)

Thanks again for your patient help to this point!

**Comment by robnewman** [comment]
FYI resolved. For some reason, my venv got deactivated (even though I still have the `venv` prompt on my CLI -- go figure). It became apparent after I tried to install another jupyter extension which also failed. Checking my `nbextensions` list:

    $ jupyter nbextension list
    Known nbextensions:
      config dir: /anaconda2/etc/jupyter/nbconfig
        notebook section
          jupyter-js-widgets/extension  enabled 
          - Validating: OK 

Wrong location! Deactivating/reactivating the venv resolved it:

    $ jupyter nbextension list
    Known nbextensions:
      config dir: /path/to/venv/quilt-py3/etc/jupyter/nbconfig
        notebook section
          rise/main  enabled 
          - Validating: OK
          jupyter-js-widgets/extension  enabled 
          - Validating: OK

Then, updating to the latest Yarn (currently v.1.6.0) as per the linked thread solved the problem.

Thanks again @meffij!
